// Code generated by scripts/gen-contracts.mjs from contracts/errors.yaml. DO NOT EDIT.
// 契约改动请改 contracts/，然后执行 make gen。

package contract

// ErrorCode 是稳定的对外错误码。
type ErrorCode = string

// 全部稳定错误码（与 internal/platform/errors.go 双向校验）。
const (
	CodeConflict         ErrorCode = "conflict"
	CodeContentPolicy    ErrorCode = "content_policy"
	CodeForbidden        ErrorCode = "forbidden"
	CodeInternal         ErrorCode = "internal"
	CodeInterrupted      ErrorCode = "interrupted"
	CodeInvalidGeometry  ErrorCode = "invalid_geometry"
	CodeInvalidID        ErrorCode = "invalid_id"
	CodeInvalidNodeType  ErrorCode = "invalid_node_type"
	CodeInvalidRequest   ErrorCode = "invalid_request"
	CodeInvalidSpec      ErrorCode = "invalid_spec"
	CodeNotFound         ErrorCode = "not_found"
	CodeNotImplemented   ErrorCode = "not_implemented"
	CodePayloadTooLarge  ErrorCode = "payload_too_large"
	CodePluginPermission ErrorCode = "plugin_permission_denied"
	CodeQuotaExceeded    ErrorCode = "quota_exceeded"
	CodeRateLimited      ErrorCode = "rate_limited"
	CodeSSRFBlocked      ErrorCode = "ssrf_blocked"
	CodeUnauthorized     ErrorCode = "unauthorized"
	CodeUnknownField     ErrorCode = "unknown_field"
	CodeUpstreamInvalid  ErrorCode = "upstream_invalid"
	CodeUpstreamRateLim  ErrorCode = "upstream_rate_limited"
)

// AllErrorCodes 返回全部错误码，供测试穷举。
var AllErrorCodes = []ErrorCode{
	"conflict",
	"content_policy",
	"forbidden",
	"internal",
	"interrupted",
	"invalid_geometry",
	"invalid_id",
	"invalid_node_type",
	"invalid_request",
	"invalid_spec",
	"not_found",
	"not_implemented",
	"payload_too_large",
	"plugin_permission_denied",
	"quota_exceeded",
	"rate_limited",
	"ssrf_blocked",
	"unauthorized",
	"unknown_field",
	"upstream_invalid",
	"upstream_rate_limited",
}

// I18nKeys 返回错误码对应的 i18n key（前端 errors.<code>）。
func I18nKey(code ErrorCode) string { return "errors." + code }
