// Code generated by scripts/gen-contracts.mjs from contracts/errors.yaml + events.yaml. DO NOT EDIT.
// 契约改动请改 contracts/，然后执行 make gen。

/** 稳定的对外错误码（与 Go 侧 internal/platform/errors.go 双向校验）。 */
export type ErrorCode =
  | "conflict"
  | "content_policy"
  | "forbidden"
  | "internal"
  | "interrupted"
  | "invalid_geometry"
  | "invalid_id"
  | "invalid_node_type"
  | "invalid_request"
  | "invalid_spec"
  | "not_found"
  | "not_implemented"
  | "payload_too_large"
  | "plugin_permission_denied"
  | "quota_exceeded"
  | "rate_limited"
  | "ssrf_blocked"
  | "unauthorized"
  | "unknown_field"
  | "upstream_invalid"
  | "upstream_rate_limited";

/** 全部错误码，供测试穷举。 */
export const ERROR_CODES = [
  "conflict",
  "content_policy",
  "forbidden",
  "internal",
  "interrupted",
  "invalid_geometry",
  "invalid_id",
  "invalid_node_type",
  "invalid_request",
  "invalid_spec",
  "not_found",
  "not_implemented",
  "payload_too_large",
  "plugin_permission_denied",
  "quota_exceeded",
  "rate_limited",
  "ssrf_blocked",
  "unauthorized",
  "unknown_field",
  "upstream_invalid",
  "upstream_rate_limited",
] as const;

/** 错误码 → i18n key。 */
export function errorI18nKey(code: string): string {
  return ERROR_CODES.includes(code as ErrorCode)
    ? `errors.${code}`
    : "errors.internal";
}

/** 画布实时事件类型（contracts/events.yaml）。 */
export type CanvasEventType =
  | "agent.item"
  | "agent.turn"
  | "canvas.op"
  | "canvas.presence"
  | "canvas.snapshot"
  | "run.finished"
  | "run.step.failed"
  | "run.step.retrying"
  | "run.step.started"
  | "run.step.succeeded"
  | "run.step.writeback_failed";

/** 全部画布事件类型。 */
export const CANVAS_EVENT_TYPES = [
  "agent.item",
  "agent.turn",
  "canvas.op",
  "canvas.presence",
  "canvas.snapshot",
  "run.finished",
  "run.step.failed",
  "run.step.retrying",
  "run.step.started",
  "run.step.succeeded",
  "run.step.writeback_failed",
] as const;
